export const Action_Types = {
  CREATE_FOOD: 'CREATE_FOOD',
  UPDATE_FOOD: 'UPDATE_FOOD',
  DELETE_FOOD: 'DELETE_FOOD',
  FETCH_ALL_FOOD: 'FETCH_ALL_FOOD',
  FETCH_SINGLE_FOOD: 'FETCH_SINGLE_FOOD',

  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  FETCH_ALL_USER: 'FETCH_ALL_USER',
  FETCH_SINGLE_USER: 'FETCH_SINGLE_USER',

  CREATE_ORDER: 'CREATE_ORDER',
  UPDATE_ORDER: 'UPDATE_ORDER',
  DELETE_ORDER: 'DELETE_ORDER',
  FETCH_ALL_ORDER: 'FETCH_ALL_ORDER',
  FETCH_SINGLE_ORDER: 'FETCH_SINGLE_ORDER',
}
